alias vim='nvim'
alias vi='nvim'
# alias ra='ranger'
alias ra='ranger --choosedir=$HOME/.rangerdir;LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias t='tmux'
alias tn='tmux new -s zelong'
alias t1='tmux new -s zelong'
alias t2='tmux new -s zelong_2'
